### ISSUE TITLE
Conceptos en Libro Sueldos

### ISSUE THREAD

**Issue by germankay** [Artimezoft/payroll_arg_reportes#23]
Algunos Nombres de Conceptos en libros sueldos son demasiados largos, habria que cambiar/acortar el formato del recibo.

![image](https://github.com/user-attachments/assets/18ef5d01-1117-4195-9d2f-79737ebc6ea7)

**Comment by germankay** [comment]
@lugezz Hola Euge, confirmame si es pocible algunas de las opciones que te planteo, o si hay otra opcion posible.

**Comment by lugezz** [comment]
@germankay yo haría ambas cosas. Achicar aun más la letra y limitar el largo a 30 caracteres. 

Otra observaciones, veo que los totales sigue teniendo una fuente más grande que los conceptos. El tamaño de la fuente debe ser igual en toda la hoja, salvo el título.

**Comment by lugezz** [comment]
@germankay @avdata99 Subo de vuelta otro modelo de Libro Sueldos, no hay problema de copiarlo porque no hay derecho de propiedad en esto, son muy parecidos todos los modelos.

[Libro Sueldos 2024-07.pdf](https://github.com/user-attachments/files/16600412/Libro.Sueldos.2024-07.pdf)

Prefiero sacrificar la originalidad, pero no seguir perdiendo tiempo en este reporte.

**Comment by lugezz** [comment]
@germankay  @avdata99 Les paso otro modelo de cómo sale de SAP. Es medio feo pero soluciona los anchos:

* Está en formato horizontal
* La columna del campo es única, dandole mucho mas lugar

No está tan bueno, pero quizás algunas ideas de esta puedan servir.

[Libro Sueldos 2024-01.pdf](https://github.com/user-attachments/files/16600535/Libro.Sueldos.2024-01.pdf)
